import { useMemo } from "react";
import { RefferalAPI, useLocalStorage } from "@orderly.network/hooks";
import { modal } from "@orderly.network/ui";
import { useReferralContext } from "../../../provider";
import { addQueryParam, copyText } from "../../../utils/utils";
import { EditCodeModal } from "./editCodeModal";
import { EditReferralRate } from "./editReferralRate";

export type ReferralCodeType = RefferalAPI.ReferralCode & {
  isPined?: boolean;
  isAutoGenerated?: boolean;
};

export type ReferralCodesReturns = {
  // 加mutate createReferralCode
  mutate: () => void;
  createReferralCode: () => Promise<void>;

  copyCode: (code: string) => void;
  copyLink: (code: string) => void;
  editRate: (code: ReferralCodeType) => void;
  editCode: (code: ReferralCodeType) => void;
  setPinCode: (code: string, del?: boolean) => void;
  codes?: ReferralCodeType[];
};

export const useReferralCodesScript = (): ReferralCodesReturns => {
  const {
    referralInfo,
    referralLinkUrl,
    mutate,
    generateCode,
    referralCodesStats,
  } = useReferralContext();

  const copyLink = (code: string) => {
    copyText(addQueryParam(referralLinkUrl, "ref", code));
  };
  const copyCode = (code: string) => {
    copyText(code);
  };
  const editRate = (code: ReferralCodeType) => {
    modal.show(EditReferralRate, { code: { ...code }, mutate });
  };

  const editCode = (code: ReferralCodeType) => {
    modal.show(EditCodeModal, {
      code: { ...code },
      successCallback: () => {
        mutate();
      },
    });
  };
  // 加入 createReferralCode
  const createReferralCode = async () => {
    if (!generateCode) {
      throw new Error("Generate code not available");
    }
    await generateCode.create();
  };

  const [pinCodes, setPinCodes] = useLocalStorage<string[]>(
    "orderly_referral_codes",
    [] as string[],
  );
  const setPinCode = (code: string, del?: boolean) => {
    if (del) {
      const index = pinCodes.findIndex((item: string) => item === code);
      if (index !== -1) {
        pinCodes.splice(index, 1);
      }
    } else {
      pinCodes.splice(0, 0, code);
    }

    if (pinCodes.length > 6) {
      pinCodes.splice(pinCodes.length - 1, 1);
    }

    setPinCodes([...pinCodes]);
  };

  const codes = useMemo((): ReferralCodeType[] | undefined => {
    let referralCodes: ReferralCodeType[] = [];

    // 優先使用 Legacy Orderly API
    if (referralInfo?.referrer_info?.referral_codes?.length) {
      referralCodes = referralInfo.referrer_info.referral_codes.map((item) => {
        // todo check auto generated
        if (generateCode && generateCode.code === item.code) {
          (item as ReferralCodeType).isAutoGenerated = true;
        }
        return item;
      });
    }
    // Fallback 到 orderly_refer API (referralCodesStats)
    else if (referralCodesStats?.codes?.length) {
      referralCodes = referralCodesStats.codes.map((code) => ({
        code: code.code,
        referrer_rebate_rate: code.owner_commission_ratio,
        referee_rebate_rate: code.fee_discount_rate,
        total_invites: code.total_invites,
        total_traded: code.total_traded,
        max_rebate_rate: code.owner_commission_ratio + code.fee_discount_rate,
      }));
    } else {
      return undefined;
    }

    const pinedItems: ReferralCodeType[] = [];

    for (let i = 0; i < pinCodes.length; i++) {
      const code = pinCodes[i];

      const index = referralCodes.findIndex((item) => item.code === code);
      if (index !== -1) {
        pinedItems.push({ ...referralCodes[index], isPined: true });
        referralCodes.splice(index, 1);
      }
    }
    return [...pinedItems, ...referralCodes];
  }, [
    referralInfo?.referrer_info?.referral_codes,
    referralCodesStats,
    pinCodes,
    generateCode,
  ]);

  return {
    // return 兩個
    mutate,
    createReferralCode,

    copyCode,
    copyLink,
    editRate,
    editCode,
    setPinCode,
    codes,
  };
};
